{
 "title": "Ping dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ping",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_rtt_mean_seconds{ip=\"223.5.5.5\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ping mean value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_mean_seconds{target=\"223.5.5.5\"} * 1000",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "ping loss value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ping_loss_ratio * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ping deviation ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_std_deviation_seconds{target=\"223.5.5.5\"} * 1000",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "ping best value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_best_seconds{target=\"223.5.5.5\"} * 1000",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "ping worst value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_rtt_worst_seconds{target=\"223.5.5.5\"} * 1000",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}